#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2026 powermac-nt-hal contributors
"""mkstubs.py <imports> <exports> imports.S exports.S

imports.S: for every import F, an IAT slot `__imp_F` (in .idata) and a code stub `F` that loads
the slot and jumps to hal_import_call (thunk.S), which performs the NT PowerPC descriptor call.
A line `F DATA` produces only the slot (the C side dereferences it).

The imports file may name more than one DLL.  A line `[HAL.dll]` starts a new group; imports
before any such line belong to the first `--import-dll` elf2pe is given (the HAL imports only
from ntoskrnl.exe and never says so).  Every group is emitted as a run of slots ending in a zero
slot -- the loader walks each descriptor's IAT until it reads zero -- and is announced by a
marker symbol `__impgrp_N` on its first slot, which is how elf2pe finds the group boundaries.
The DLL *names* travel on elf2pe's command line, in the same order, so that the ELF stays free
of strings the kernel's loader never reads.

exports.S: for every exported function F, the descriptor `desc_F` = { xthunk_F, 0 } and a thunk
`xthunk_F` that gives the kernel a frame of its own before calling F.

The thunk is not ceremony.  We compile for SVR4, where the LR save slot is **4(caller's r1)**;
NT PowerPC puts the *caller's saved TOC* there, written by the calling module's import glue
immediately before it jumps to us.  A C function called directly by the kernel therefore
overwrites its caller's TOC with our return address, and the caller's `lwz r2,4(r1)` after the
call loads a code address into r2 -- the next TOC-relative access then reads below the image and
bugchecks 0x50.  (That is exactly what MGA_MIL.SYS did; see STORY.md wall 49.)  thunk.S already
guards the other direction, where an NT callee writes into *our* frame."""
import sys
imports, exports, imp_s, exp_s = sys.argv[1:5]


def entries(path):
    for line in open(path):
        line = line.split('#')[0].strip()
        if line: yield line.split()


def import_groups(path):
    """[[(name, is_data), ...], ...] in file order; a `[dll]` line opens a new group."""
    groups = [[]]
    for e in entries(path):
        if e[0].startswith('[') and e[0].endswith(']'):
            if groups[-1]: groups.append([])
            continue
        groups[-1].append((e[0], len(e) > 1 and e[1].upper() == 'DATA'))
    return [g for g in groups if g]


with open(imp_s, 'w') as f:
    f.write('/* generated by mkstubs.py */\n\t.section .idata,"aw",@progbits\n\t.p2align 2\n')
    groups = import_groups(imports)
    for gi, g in enumerate(groups):
        f.write(f'\t.globl __impgrp_{gi}\n__impgrp_{gi}:\n')
        for n, _ in g:
            f.write(f'\t.globl __imp_{n}\n__imp_{n}:\t.long 0\n')
        f.write('\t.long 0\t/* the loader walks this IAT until a zero entry */\n')
    f.write('\n\t.text\n\t.p2align 2\n')
    for g in groups:
        for n, is_data in g:
            if is_data: continue
            f.write(f'\t.globl {n}\n\t.type {n},@function\n{n}:\n\tlis 11, __imp_{n}@ha\n\tlwz 11, __imp_{n}@l(11)\n\tb hal_import_call\n')
with open(exp_s, 'w') as f:
    f.write('/* generated by mkstubs.py */\n\t.data\n\t.p2align 3\n')
    funcs = [e[0] for e in entries(exports) if not (len(e) > 1 and e[1].upper() == 'DATA')]
    for n in funcs:
        f.write(f'\t.globl desc_{n}\ndesc_{n}:\t.long xthunk_{n}\n\t.long 0\n')
    f.write('\n\t.text\n\t.p2align 2\n')
    for n in funcs:
        f.write(f'\t.type xthunk_{n},@function\nxthunk_{n}:\n'
                '\tmflr\t0\n\tstwu\t1, -64(1)\n\tstw\t0, 60(1)\n'
                f'\tbl\t{n}\n'
                '\tlwz\t0, 60(1)\n\taddi\t1, 1, 64\n\tmtlr\t0\n\tblr\n')
