#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2026 powermac-nt-hal contributors
"""mkstubs.py hal.imports hal.exports imports.S exports.S

imports.S: for every kernel import F, an IAT slot `__imp_F` (in .idata) and a code stub `F`
that loads the slot and jumps to hal_import_call (thunk.S), which performs the NT PowerPC
descriptor call.  A line `F DATA` produces only the slot (the C side dereferences it).
exports.S: for every exported function F, the descriptor `desc_F` = { xthunk_F, 0 } and a
thunk `xthunk_F` that gives the kernel a frame of its own before calling F.

The thunk is not ceremony.  We compile for SVR4, where the LR save slot is **4(caller's r1)**;
NT PowerPC puts the *caller's saved TOC* there, written by the calling module's import glue
immediately before it jumps to us.  A C function called directly by the kernel therefore
overwrites its caller's TOC with our return address, and the caller's `lwz r2,4(r1)` after the
call loads a code address into r2 — the next TOC-relative access then reads below the image and
bugchecks 0x50.  (That is exactly what MGA_MIL.SYS did; see STORY.md wall 49.)  thunk.S already
guards the other direction, where an NT callee writes into *our* frame."""
import sys
imports, exports, imp_s, exp_s = sys.argv[1:5]
def entries(path):
    for line in open(path):
        line = line.split('#')[0].strip()
        if line: yield line.split()
with open(imp_s, 'w') as f:
    f.write('/* generated by mkstubs.py */\n\t.section .idata,"aw",@progbits\n\t.p2align 2\n')
    names = [e[0] for e in entries(imports)]
    for n in names:
        f.write(f'\t.globl __imp_{n}\n__imp_{n}:\t.long 0\n')
    f.write('\t.long 0\t/* the loader walks the IAT until a zero entry */\n')
    f.write('\n\t.text\n\t.p2align 2\n')
    for e in entries(imports):
        n = e[0]
        if len(e) > 1 and e[1].upper() == 'DATA': continue
        f.write(f'\t.globl {n}\n\t.type {n},@function\n{n}:\n\tlis 11, __imp_{n}@ha\n\tlwz 11, __imp_{n}@l(11)\n\tb hal_import_call\n')
with open(exp_s, 'w') as f:
    f.write('/* generated by mkstubs.py */\n\t.data\n\t.p2align 3\n')
    funcs = [e[0] for e in entries(exports) if not (len(e) > 1 and e[1].upper() == 'DATA')]
    for n in funcs:
        f.write(f'\t.globl desc_{n}\ndesc_{n}:\t.long xthunk_{n}\n\t.long 0\n')
    f.write('\n\t.text\n\t.p2align 2\n')
    for n in funcs:
        f.write(f'\t.type xthunk_{n},@function\nxthunk_{n}:\n'
                '\tmflr\t0\n\tstwu\t1, -64(1)\n\tstw\t0, 60(1)\n'
                f'\tbl\t{n}\n'
                '\tlwz\t0, 60(1)\n\taddi\t1, 1, 64\n\tmtlr\t0\n\tblr\n')
