#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2026 powermac-nt-hal contributors
"""mkstubs.py hal.imports hal.exports imports.S exports.S

imports.S: for every kernel import F, an IAT slot `__imp_F` (in .idata) and a code stub `F`
that loads the slot and jumps to hal_import_call (thunk.S), which performs the NT PowerPC
descriptor call.  A line `F DATA` produces only the slot (the C side dereferences it).
exports.S: for every exported function F, the descriptor `desc_F` = { F, 0 } in .data."""
import sys
imports, exports, imp_s, exp_s = sys.argv[1:5]
def entries(path):
    for line in open(path):
        line = line.split('#')[0].strip()
        if line: yield line.split()
with open(imp_s, 'w') as f:
    f.write('/* generated by mkstubs.py */\n\t.section .idata,"aw",@progbits\n\t.p2align 2\n')
    names = [e[0] for e in entries(imports)]
    for n in names:
        f.write(f'\t.globl __imp_{n}\n__imp_{n}:\t.long 0\n')
    f.write('\t.long 0\t/* the loader walks the IAT until a zero entry */\n')
    f.write('\n\t.text\n\t.p2align 2\n')
    for e in entries(imports):
        n = e[0]
        if len(e) > 1 and e[1].upper() == 'DATA': continue
        f.write(f'\t.globl {n}\n\t.type {n},@function\n{n}:\n\tlis 11, __imp_{n}@ha\n\tlwz 11, __imp_{n}@l(11)\n\tb hal_import_call\n')
with open(exp_s, 'w') as f:
    f.write('/* generated by mkstubs.py */\n\t.data\n\t.p2align 3\n')
    for e in entries(exports):
        n = e[0]
        if len(e) > 1 and e[1].upper() == 'DATA': continue
        f.write(f'\t.globl desc_{n}\ndesc_{n}:\t.long {n}\n\t.long 0\n')
